# config.yml (v13.0)

# 기본 데이터센터 설정
dc_defaults:
  size_mw: 100
  amortization_years: 5
  capex_per_mw: 1000000         # USD
  opex_per_mw_per_year: 150000  # USD
  power_cost_kwh:
    Conventional: 0.12          # USD
    Renewable: 0.18

# LLM 토큰 처리 효율
token_processing:
  token_per_kwh: 2000
  # 지능형 아키텍처 적용 시 효율 개선 배수
  mirrormind_efficiency: 1.25

# 사용자 분포 및 사용량
tiers:
  free:
    ratio: 0.6
    monthly_token_usage: 30000
  standard:
    ratio: 0.3
    monthly_token_usage: 300000
  premium:
    ratio: 0.1
    monthly_token_usage: 3000000

# 일반 설정
assumptions:
  users_total: 1000000
