# Overall simulation period in years
simulation_period_years: 5

# ===============================================
# Technical & Cost Parameters for Energy Sources
# - All sources are now at the same level for simplicity and robustness.
# ===============================================

energy_sources:
  # Grid Power
  grid:
    price_per_kwh: 0.12            # Initial purchase price per kWh ($)
    carbon_emission_factor: 0.45   # kg CO2 per kWh

  # Solar PV
  solar:
    capex_per_kw: 1000             # Initial capital expenditure ($/kW)
    opex_rate: 0.015               # Annual O&M cost rate (as a fraction of CAPEX)
    capacity_factor: 0.18          # Annual average capacity factor (%)

  # Wind
  wind:
    capex_per_kw: 1500             # Initial capital expenditure ($/kW)
    opex_rate: 0.02                # Annual O&M cost rate (as a fraction of CAPEX)
    capacity_factor: 0.30          # Annual average capacity factor (%)

  # Hydrogen Fuel Cell (SOFC)
  hydrogen_SOFC:
    capex_per_kw: 2800             # Initial capital expenditure ($/kW)
    opex_rate: 0.02                # Annual O&M cost rate (as a fraction of CAPEX)
    efficiency: 0.60               # Power generation efficiency (%)
    stack_lifetime_years: 3        # Stack replacement cycle (years)
    stack_replacement_cost_rate: 0.4 # Stack replacement cost (as a fraction of initial CAPEX)
