# Overall simulation period in years
simulation_period_years: 5

# Asset lifetime for LCOE calculation (years)
asset_lifetime_years: 20

# ===============================================
# Market Scenarios
# - Defines region-specific energy prices based on recent data.
# ===============================================
market_scenarios:
  USA_Virginia_DC:
    description: "Hyperscale data center hub. Price reflects total cost of securing power, not just retail rate."
    grid_price_per_kwh: 0.16
    gas_fuel_cost_per_kwh: 0.07 
  South_Korea_Industrial:
    description: "High industrial electricity rates and reliance on imported fuel."
    grid_price_per_kwh: 0.13
    gas_fuel_cost_per_kwh: 0.11
  EU_Germany_Frankfurt:
    description: "Major EU hub with high electricity prices due to taxes and grid fees."
    grid_price_per_kwh: 0.22
    gas_fuel_cost_per_kwh: 0.09
  EU_Nordics_Favorable:
    description: "Low power costs due to abundant renewable energy (hydro/wind)."
    grid_price_per_kwh: 0.07
    gas_fuel_cost_per_kwh: 0.09

# ===============================================
# Technical & Cost Parameters for Energy Sources
# ===============================================
energy_sources:
  # Grid Power (Price is now loaded from market_scenarios)
  grid:
    carbon_emission_factor: 0.45

  # Solar PV
  solar:
    capex_per_kw: 1500
    opex_rate: 0.015
    capacity_factor: 0.18

  # Wind
  wind:
    capex_per_kw: 2000
    opex_rate: 0.02
    capacity_factor: 0.30

  # Hydrogen Fuel Cell (SOFC)
  hydrogen_SOFC:
    capex_per_kw: 3500
    opex_rate: 0.02
    efficiency: 0.60
    stack_lifetime_years: 5
    stack_replacement_cost_rate: 0.3
  
  # Natural Gas Fuel Cell (NG-SOFC)
  NG_SOFC:
    capex_per_kw: 3500
    opex_rate: 0.025
    efficiency: 0.55
    carbon_emission_factor: 0.4
