# ===============================================
# Business & Financial Assumptions
# ===============================================
business_assumptions:
  analysis_years: 10 # 사업 타당성 분석 기간 (년)

# ===============================================
# User & Pricing Model Assumptions (Unit Economics)
# ===============================================
user_assumptions:
  total_users_for_100mw: 150000 # 100MW DC 기준 총 사용자 수
  tiers:
    free:
      ratio: 0.70 # 전체 사용자 중 70%
      monthly_token_usage_millions: 0.1 # 월간 10만 토큰 사용
    paid:
      ratio: 0.25 # 전체 사용자 중 25%
      monthly_token_usage_millions: 2.0 # 월간 200만 토큰 사용
    premium:
      ratio: 0.05 # 전체 사용자 중 5%
      monthly_token_usage_millions: 10.0 # 월간 1000만 토큰 사용

# ===============================================
# Infrastructure & Hardware Assumptions
# ===============================================
infrastructure_assumptions:
  dc_construction_cost_per_mw: 10000000
  low_cost_hw_penalty_factor: 1.2
  high_perf_gpu:
    name: "NVIDIA H100"
    cost_per_unit: 35000
    performance_unit: 10
  low_cost_gpu:
    name: "NVIDIA A4000"
    cost_per_unit: 1200
    performance_unit: 1
  maintenance_rate_of_construction_capex: 0.02
  building_depreciation_years: 40
  it_hw_depreciation_years: 5
  corporate_tax_rate: 0.25

# ===============================================
# Service & Architecture Assumptions
# ===============================================
advanced_architecture_assumptions:
  workload_efficiency_factor: 0.167 # Equivalent to 83.3% reduction

service_unit_assumptions:
  tokens_processed_per_mwh: 3000000000 # 3 billion tokens

# ===============================================
# Electricity Pricing Scenarios
# ===============================================
electricity_pricing_scenarios:
  standard_grid:
    price_per_kwh: 0.13 # Represents a baseline industrial rate
  net_zero_ppa:
    price_per_kwh: 0.20 # Represents a premium for a 100% renewable PPA

