# Overall simulation period in years
simulation_period_years: 5

# ===============================================
# Strategic & Financial Assumptions
# ===============================================
strategic_assumptions:
  viability_analysis_years: 10 # 사업 타당성 분석 기간 (년)
  high_perf_gpu:
    name: "NVIDIA H100"
    cost_per_unit: 35000
    performance_unit: 10
  low_cost_gpu:
    name: "NVIDIA A4000"
    cost_per_unit: 1200
    performance_unit: 1
  dc_construction_cost_per_mw: 10000000
  low_cost_hw_penalty_factor: 1.2
  building_depreciation_years: 40
  it_hw_depreciation_years: 5
  corporate_tax_rate: 0.25
  maintenance_rate_of_construction_capex: 0.02

# ===============================================
# Revenue & Business Viability Assumptions
# ===============================================
revenue_assumptions:
  tokens_processed_per_mwh: 3000000000 # 3 billion tokens
  active_users_per_mw: 1500

# ===============================================
# User & Pricing Model Assumptions
# ===============================================
user_assumptions:
  assumed_low_tier_fee: 20.0
  high_to_low_pricing_ratio: 5
  total_users: 150000
  low_tier_user_pct: 0.9
  high_tier_user_pct: 0.1

# ===============================================
# Advanced Architecture Assumptions
# ===============================================
advanced_architecture_assumptions:
  workload_efficiency_factor: 0.167 # Equivalent to 83.3% reduction

# ===============================================
# Power Mix Configurations
# ===============================================
power_mix_options:
  carbon_free_mix:
    grid: 40
    solar: 40
    wind: 0
    hydrogen_SOFC: 0
    NG_SOFC: 20
  standard_mix:
    grid: 80
    solar: 0
    wind: 0
    hydrogen_SOFC: 0
    NG_SOFC: 20

# ===============================================
# Market Scenarios & Electricity Pricing
# ===============================================
electricity_pricing_scenarios:
  standard_grid:
    price_per_kwh: 0.13 # Represents a baseline industrial rate
  net_zero_ppa:
    price_per_kwh: 0.20 # Represents a premium for a 100% renewable PPA
