# config.yml (v18.0 - User-centric metrics)

# ===============================================
# 투자 및 자산 (Investment & Assets)
# ===============================================
investment:
  dc_capex_per_mw: 10000000
  it_budget_per_mw: 12500000
  amortization_years:
    datacenter: 40
    it_hardware: 5
    research_and_development: 3

# ===============================================
# 하드웨어 스펙 (Hardware Specs)
# ===============================================
hardware:
  high_perf_gpu:
    cost: 35000
    m_tokens_per_hour: 5.0
  standard_gpu:
    cost: 10000
    m_tokens_per_hour: 1.5

# ===============================================
# 운영 비용 (Operating Expenses)
# ===============================================
operating_expenses:
  maintenance_and_cooling_per_mw: 250000
  personnel_and_other_per_mw: 350000
  sgna_as_percent_of_revenue: 15.0
  pue: 1.5

# ===============================================
# 연구개발 (R&D)
# ===============================================
research_and_development:
  total_model_development_cost: 2000000000
  global_datacenter_count_for_cost_allocation: 20

# ===============================================
# AI 모델 및 시장 가격
# ===============================================
model_and_market:
  intelligent_arch_efficiency: 1.25
  market_price_per_million_tokens: 1.5
  # [NEW] 100MW DC 기준, 총 사용자 수 (인당 지표 계산용)
  total_users_for_100mw: 1000000
  # 사용자 그룹별 분포 및 월간 토큰 사용량 (백만 개)
  tiers:
    free:
      ratio: 0.6
      monthly_token_usage_m: 0.5
    standard:
      ratio: 0.3
      monthly_token_usage_m: 5.0
    premium:
      ratio: 0.1
      monthly_token_usage_m: 25.0

