# Overall simulation period in years
simulation_period_years: 5

# ===============================================
# Strategic & Financial Assumptions
# ===============================================
strategic_assumptions:
  viability_analysis_years: 10 # 사업 타당성 분석 기간 (년)
  high_perf_gpu:
    name: "NVIDIA H100"
    cost_per_unit: 35000
    performance_unit: 10
  low_cost_gpu:
    name: "NVIDIA A4000"
    cost_per_unit: 1200
    performance_unit: 1
  dc_construction_cost_per_mw: 10000000
  low_cost_hw_penalty_factor: 1.2
  building_depreciation_years: 40
  it_hw_depreciation_years: 5
  corporate_tax_rate: 0.25
  maintenance_rate_of_construction_capex: 0.02

# ===============================================
# Revenue & Business Viability Assumptions
# ===============================================
revenue_assumptions:
  tokens_processed_per_mwh: 3000000000 # 3 billion tokens
  active_users_per_mw: 1500

# ===============================================
# Advanced Architecture Assumptions
# ===============================================
advanced_architecture_assumptions:
  workload_efficiency_factor: 0.167 # Equivalent to 83.3% reduction

# ===============================================
# Power Mix Configurations
# ===============================================
power_mix_options:
  carbon_free_mix:
    grid: 40
    solar: 40
    wind: 0
    hydrogen_SOFC: 0
    NG_SOFC: 20
  standard_mix:
    grid: 80
    solar: 0
    wind: 0
    hydrogen_SOFC: 0
    NG_SOFC: 20

# ===============================================
# Market Scenarios
# ===============================================
market_scenarios:
  USA_California_HighCost:
    description: "Represents a high-cost region with expensive electricity and stringent regulations. (e.g., Silicon Valley)"
    grid_price_per_kwh: 0.24
    gas_fuel_cost_per_kwh: 0.08
  USA_Virginia_AvgCost:
    description: "A major data center hub with relatively average power costs. (e.g., Data Center Alley)"
    grid_price_per_kwh: 0.16
    gas_fuel_cost_per_kwh: 0.07 
  USA_Washington_LowCost:
    description: "Represents a low-cost region with abundant and cheap hydropower."
    grid_price_per_kwh: 0.11
    gas_fuel_cost_per_kwh: 0.07
  South_Korea_Industrial:
    description: "High industrial electricity rates and reliance on imported fuel."
    grid_price_per_kwh: 0.13
    gas_fuel_cost_per_kwh: 0.11
  EU_Germany_Frankfurt:
    description: "Major EU hub with high electricity prices due to taxes and grid fees."
    grid_price_per_kwh: 0.22
    gas_fuel_cost_per_kwh: 0.09
  EU_Nordics_Favorable:
    description: "Low power costs due to abundant renewable energy (hydro/wind)."
    grid_price_per_kwh: 0.07
    gas_fuel_cost_per_kwh: 0.09

# ===============================================
# Technical & Cost Parameters for Energy Sources
# ===============================================
energy_sources:
  grid:
    carbon_emission_factor: 0.45
  solar:
    capex_per_kw: 1500
    opex_rate: 0.015
    capacity_factor: 0.18
  wind:
    capex_per_kw: 2000
    opex_rate: 0.02
    capacity_factor: 0.30
  hydrogen_SOFC:
    capex_per_kw: 3500
    opex_rate: 0.02
    efficiency: 0.60
    stack_lifetime_years: 5
    stack_replacement_cost_rate: 0.3
  NG_SOFC:
    capex_per_kw: 3500
    opex_rate: 0.025
    efficiency: 0.55
    carbon_emission_factor: 0.4
