# Overall simulation period in years
simulation_period_years: 5

# Asset lifetime for LCOE calculation (years)
asset_lifetime_years: 20

# ===============================================
# Market Scenarios
# - Defines region-specific energy prices.
# ===============================================
market_scenarios:
  USA_Virginia:
    description: "Major data center hub with competitive but rising power costs."
    # Grid price is now defined in the main energy_sources section
    gas_fuel_cost_per_kwh: 0.07 
  South_Korea:
    description: "High industrial electricity rates and reliance on imported fuel."
    # Grid price is now defined in the main energy_sources section
    gas_fuel_cost_per_kwh: 0.11
  EU_Nordics:
    description: "Low power costs due to abundant renewable energy (hydro/wind)."
    # Grid price is now defined in the main energy_sources section
    gas_fuel_cost_per_kwh: 0.09

# ===============================================
# Technical & Cost Parameters for Energy Sources
# - These values are updated based on real market data.
# ===============================================
energy_sources:
  # Grid Power
  grid:
    price_per_kwh: 0.20            # Initial purchase price per kWh ($)
    carbon_emission_factor: 0.45   # kg CO2 per kWh

  # Solar PV
  solar:
    capex_per_kw: 1500             # Initial capital expenditure ($/kW)
    opex_rate: 0.015               # Annual O&M cost rate (as a fraction of CAPEX)
    capacity_factor: 0.18          # Annual average capacity factor (%)

  # Wind
  wind:
    capex_per_kw: 2000             # Initial capital expenditure ($/kW)
    opex_rate: 0.02                # Annual O&M cost rate (as a fraction of CAPEX)
    capacity_factor: 0.30          # Annual average capacity factor (%)

  # Hydrogen Fuel Cell (SOFC)
  hydrogen_SOFC:
    capex_per_kw: 3500             # Initial capital expenditure ($/kW)
    opex_rate: 0.02                # Annual O&M cost rate (as a fraction of CAPEX)
    efficiency: 0.60               # Power generation efficiency (%)
    stack_lifetime_years: 5        # Stack replacement cycle (years)
    stack_replacement_cost_rate: 0.3 # Stack replacement cost (as a fraction of initial CAPEX)
  
  # Natural Gas Fuel Cell (NG-SOFC) - Kept for comparison if needed
  NG_SOFC:
    capex_per_kw: 3500
    opex_rate: 0.025
    efficiency: 0.55
    carbon_emission_factor: 0.4
