# ===============================================
# Core Business & Financial Assumptions
# ===============================================
business_assumptions:
  analysis_years: 3
  target_irr: 0.08
  annual_rd_personnel_cost: 50000000 # 연간 R&D 인건비

# ===============================================
# AI Model Specific Assumptions
# ===============================================
model_assumptions:
  training_cost: 100000000 # 모델 훈련 비용 (초기 1회 발생)

# ===============================================
# User Base and Pricing Assumptions
# ===============================================
user_assumptions:
  total_users: 1000000
  free_user_pct: 0.60
  low_tier_user_pct: 0.30
  high_tier_user_pct: 0.10
  high_to_low_pricing_ratio: 10 # 고사용자:저사용자 요금 비율

# ===============================================
# Infrastructure Model Parameters
# ===============================================
infrastructure_models:
  cloud:
    name: "Cloud-Based Operation"
    # 연간 클라우드 인프라 운영 비용
    annual_opex: 400000000 
  
  on_premise:
    name: "On-Premise Infrastructure"
    # 초기 투자 비용 (CAPEX)
    initial_capex_server: 500000000
    initial_capex_facility: 300000000
    # 연간 온프레미스 인프라 운영 비용
    annual_opex: 150000000
    # 감가상각 내용연수 (세금 계산용)
    depreciation_years_server: 5
    depreciation_years_facility: 15
    # 법인세율
    corporate_tax_rate: 0.25
