# ===============================================
# Business & Financial Assumptions
# ===============================================
business_assumptions:
  analysis_years: 10 # 사업 타당성 분석 기간 (년)

user_assumptions:
  assumed_low_tier_fee: 20.0
  high_to_low_pricing_ratio: 5
  total_users: 150000
  low_tier_user_pct: 0.9
  high_tier_user_pct: 0.1

# ===============================================
# Infrastructure & Hardware Assumptions
# ===============================================
infrastructure_assumptions:
  dc_construction_cost_per_mw: 10000000
  low_cost_hw_penalty_factor: 1.2
  high_perf_gpu:
    name: "NVIDIA H100"
    cost_per_unit: 35000
    performance_unit: 10
  low_cost_gpu:
    name: "NVIDIA A4000"
    cost_per_unit: 1200
    performance_unit: 1
  maintenance_rate_of_construction_capex: 0.02
  building_depreciation_years: 40
  it_hw_depreciation_years: 5
  corporate_tax_rate: 0.25

# ===============================================
# Service & Architecture Assumptions
# ===============================================
advanced_architecture_assumptions:
  workload_efficiency_factor: 0.167 # Equivalent to 83.3% reduction

service_unit_assumptions:
  tokens_processed_per_mwh: 3000000000 # 3 billion tokens

# ===============================================
# Electricity Pricing Scenarios
# ===============================================
electricity_pricing_scenarios:
  standard_grid:
    price_per_kwh: 0.13 # Represents a baseline industrial rate
  net_zero_ppa:
    price_per_kwh: 0.20 # Represents a premium for a 100% renewable PPA
