# ===============================================
# Business & Financial Assumptions
# ===============================================
business_assumptions:
  # 100MW급 데이터센터를 짓는 데 필요한 총 투자 예산 (IT 하드웨어 제외)
  dc_construction_budget: 1000000000 # 10억 달러
  # IT 하드웨어에 투자할 총 예산
  it_hardware_budget: 700000000 # 7억 달러

# ===============================================
# Performance & Cost Assumptions
# ===============================================
performance_assumptions:
  # 고성능 GPU (예: H100)
  high_perf_gpu:
    cost_per_unit: 35000
    performance_score_per_unit: 100 # 상대적 성능 점수
  # 저비용 GPU (예: A4000)
  low_cost_gpu:
    cost_per_unit: 1200
    performance_score_per_unit: 10 # 상대적 성능 점수
  
  # 성능 점수 1점이 1시간 동안 처리할 수 있는 토큰의 양 (백만 개 단위)
  m_tokens_per_hour_per_performance_score: 0.05

# ===============================================
# User & Pricing Model Assumptions
# ===============================================
user_assumptions:
  # 이 사용자 조합을 '1개 사용자 세트'로 정의
  user_set_composition:
    free:
      ratio: 70
      monthly_token_usage_millions: 0.1
    paid:
      ratio: 25
      monthly_token_usage_millions: 2.0
    premium:
      ratio: 5
      monthly_token_usage_millions: 10.0
  
  # 유료 및 프리미엄 사용자 월 요금
  pricing:
    paid_tier_fee: 20.0
    premium_tier_fee: 100.0

# ===============================================
# Other Operating Assumptions
# ===============================================
operating_assumptions:
  # 데이터센터 건설비에 대한 연간 유지보수비 비율
  maintenance_rate_of_construction_capex: 0.02
  # 감가상각 기간 (년)
  building_depreciation_years: 40
  it_hw_depreciation_years: 5
  # 전력 비용 ($/kWh)
  electricity_price_per_kwh: 0.13
  # 데이터센터 전력효율지수 (PUE)
  pue: 1.5
  # IT 장비의 전력 소모량 (와트 / 달러 기준)
  watts_per_dollar_of_it_hardware: 0.025

