# ===============================================
# Business & Financial Assumptions
# ===============================================
business_assumptions:
  analysis_years: 10
  corporate_tax_rate: 0.25

# ===============================================
# Infrastructure & Hardware Assumptions
# ===============================================
infrastructure_assumptions:
  dc_construction_cost_per_mw: 10000000
  it_hardware_budget_per_mw: 7000000
  building_depreciation_years: 40
  it_hw_depreciation_years: 5
  pue: 1.5
  watts_per_dollar_of_it_hardware: 0.025
  maintenance_rate_of_construction_capex: 0.02

# ===============================================
# Hardware Performance Specs
# ===============================================
hardware_specs:
  high_perf_gpu:
    cost_per_unit: 35000
    m_tokens_per_hour_per_unit: 5.0
  low_cost_gpu:
    cost_per_unit: 1200
    m_tokens_per_hour_per_unit: 0.5

# ===============================================
# Advanced Architecture (e.g., MirrorMind)
# ===============================================
advanced_architecture:
  workload_efficiency_factor: 0.2

# ===============================================
# User & Pricing Model
# ===============================================
user_model:
  user_set_composition:
    free: { ratio: 70, monthly_token_usage_millions: 0.1 }
    paid: { ratio: 25, monthly_token_usage_millions: 2.0 }
    premium: { ratio: 5, monthly_token_usage_millions: 10.0 }
  pricing:
    paid_tier_fee: 20.0
    premium_tier_fee: 100.0

# ===============================================
# Electricity Pricing Scenarios
# ===============================================
electricity_scenarios:
  standard_grid:
    price_per_kwh: 0.20
  net_zero_ppa:
    price_per_kwh: 0.25 # Premium for 100% renewable

