{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/HWAN-OH/H2-Energy-for-AI-DC-Mix-Simulator/blob/main/localization.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# localization.py\n",
        "# UI 텍스트를 위한 한/영 문자열 저장소\n",
        "\n",
        "loc_strings = {\n",
        "    'ko': {\n",
        "        'app_title': \"💡 AI 데이터센터 통합 TCO & 전략 시뮬레이터 (v2.1)\",\n",
        "        'app_subtitle': \"IT 하드웨어, 아키텍처, 건설 및 에너지 비용을 통합하여 최적의 데이터센터 투자 전략을 분석합니다.\",\n",
        "        'sidebar_title': \"⚙️ 시나리오 구성\",\n",
        "        'lang_selector_label': \"언어 (Language)\",\n",
        "        'section_1_header': \"1. 핵심 전략 선택\",\n",
        "        'mirrormind_toggle_label': \"**MirrorMind 아키텍처 적용**\",\n",
        "        'mirrormind_toggle_help': \"\"\"\n",
        "        **적용 시:** AI 워크로드 효율화(필요 연산량 83.3% 감소) 및 에너지 믹스 최적화.\n",
        "        **미적용 시:** 표준 워크로드 및 에너지 믹스.\n",
        "        (참고: 효율화 효과는 '미러마인드 도입 제안서'의 가설에 기반합니다.)\n",
        "        \"\"\",\n",
        "        'hw_ratio_label': \"**고성능 하드웨어(H100) 비중 (%)**\",\n",
        "        'hw_ratio_help': \"\"\"\n",
        "        전체 AI 워크로드 중 고성능 칩으로 처리해야 하는 비율.\n",
        "        0%는 모든 작업을 저비용 칩으로 처리, 100%는 모든 작업을 고성능 칩으로 처리함을 의미합니다.\n",
        "        \"\"\",\n",
        "        'section_2_header': \"2. 시장 및 경제 가정\",\n",
        "        'market_label': \"시장 / 지역\",\n",
        "        'discount_rate_label': \"할인율 (%)\",\n",
        "        'run_button_label': \"🚀 TCO 분석 실행\",\n",
        "        'spinner_text': \"TCO 분석 중...\",\n",
        "        'results_header': \"📊 분석 결과\",\n",
        "        'user_scenario_header': \"나의 시나리오 결과\",\n",
        "        'tco_metric_label': \"5년 최종 통합 TCO\",\n",
        "        'investment_metric_label': \"단위 MW당 최종 투자 비용\",\n",
        "        'comparison_header': \"4대 핵심 전략 옵션 비교 기준점\",\n",
        "        'strategy_col_1': \"전략 옵션\",\n",
        "        'strategy_col_2': \"핵심 전략\",\n",
        "        'strategy_col_3': \"단위 MW당 투자 비용\",\n",
        "        'option_1_name': \"옵션 1: 현상 유지\",\n",
        "        'option_2_name': \"옵션 2: 잘못된 경제학\",\n",
        "        'option_3_name': \"옵션 3: 최적 경로\",\n",
        "        'option_4_name': \"옵션 4: 실행 가능한 대안\",\n",
        "        'strategy_1_desc': \"고성능 (미적용)\",\n",
        "        'strategy_2_desc': \"저비용 (미적용)\",\n",
        "        'strategy_3_desc': \"고성능 (적용)\",\n",
        "        'strategy_4_desc': \"저비용 (적용)\",\n",
        "        'footer_text': \"© 2025, OH SEONG-HWAN. 본 시뮬레이터는 전략적 의사결정을 위한 개념적 도구입니다.\"\n",
        "    },\n",
        "    'en': {\n",
        "        'app_title': \"💡 AI DC Integrated TCO & Strategy Simulator (v2.1)\",\n",
        "        'app_subtitle': \"Analyze the optimal data center investment strategy by integrating IT hardware, architecture, construction, and energy costs.\",\n",
        "        'sidebar_title': \"⚙️ Scenario Configuration\",\n",
        "        'lang_selector_label': \"Language\",\n",
        "        'section_1_header': \"1. Core Strategic Choices\",\n",
        "        'mirrormind_toggle_label': \"**Apply MirrorMind Architecture**\",\n",
        "        'mirrormind_toggle_help': \"\"\"\n",
        "        **On:** Enables AI workload efficiency (83.3% reduction in required computation) and optimizes the energy mix.\n",
        "        **Off:** Uses standard workload and energy mix.\n",
        "        (Note: The efficiency effect is based on the hypothesis in the 'MirrorMind Adoption Proposal'.)\n",
        "        \"\"\",\n",
        "        'hw_ratio_label': \"**High-Performance HW (H100) Ratio (%)**\",\n",
        "        'hw_ratio_help': \"\"\"\n",
        "        The percentage of the total AI workload that must be processed by high-performance chips.\n",
        "        0% means all tasks are handled by low-cost chips; 100% means all tasks are handled by high-performance chips.\n",
        "        \"\"\",\n",
        "        'section_2_header': \"2. Market & Economic Assumptions\",\n",
        "        'market_label': \"Market / Region\",\n",
        "        'discount_rate_label': \"Discount Rate (%)\",\n",
        "        'run_button_label': \"🚀 Run TCO Analysis\",\n",
        "        'spinner_text': \"Analyzing TCO...\",\n",
        "        'results_header': \"📊 Analysis Results\",\n",
        "        'user_scenario_header': \"My Scenario's Result\",\n",
        "        'tco_metric_label': \"5-Year Final Integrated TCO\",\n",
        "        'investment_metric_label': \"Final Investment per MW\",\n",
        "        'comparison_header': \"Benchmark: 4 Key Strategic Options\",\n",
        "        'strategy_col_1': \"Strategic Option\",\n",
        "        'strategy_col_2': \"Core Strategy\",\n",
        "        'strategy_col_3': \"Investment per MW\",\n",
        "        'option_1_name': \"Option 1: The Incumbent\",\n",
        "        'option_2_name': \"Option 2: The False Economy\",\n",
        "        'option_3_name': \"Option 3: The Optimal Path\",\n",
        "        'option_4_name': \"Option 4: The Viable Alternative\",\n",
        "        'strategy_1_desc': \"High-Perf (No MM)\",\n",
        "        'strategy_2_desc': \"Low-Cost (No MM)\",\n",
        "        'strategy_3_desc': \"High-Perf (w/ MM)\",\n",
        "        'strategy_4_desc': \"Low-Cost (w/ MM)\",\n",
        "        'footer_text': \"© 2025, OH SEONG-HWAN. This is a conceptual simulator for strategic decision-making.\"\n",
        "    }\n",
        "}"
      ],
      "outputs": [],
      "execution_count": null,
      "metadata": {
        "id": "dDloc__YU3Yq"
      }
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}