# localization.py (v21.0 - Pricing Strategy)

loc_strings = {
    "en": {
        "app_title": "AI Datacenter Business Simulator",
        "app_subtitle": "A strategic tool to analyze the real-world P&L of AI services.",
        "sidebar_guide_title": "📖 How to Use",
        "sidebar_guide_text": "Adjust the variables below and click 'Run Analysis' to see the financial forecast.",
        "copyright_text": "© 2025, Oh Sunghwan. All rights reserved.",
        "contact_text": "Contact: hawn21@gmail.com",
        "lang_selector": "Language",
        "dc_capacity": "Data Center Size (MW)",
        "high_perf_gpu_ratio": "High-Performance GPU Budget Ratio (%)",
        "utilization_rate": "Datacenter Average Utilization Rate (%)",
        "power_type": "Power Source",
        "apply_mirrormind": "Apply Intelligent Architecture",
        "market_price": "Market Price per 1M Tokens ($)",
        "run_button": "🚀 Run Analysis",
        "initial_prompt": "Set your scenario variables in the sidebar and click 'Run Analysis'.",
        "section_1_title": "1. Overall Business P&L (Annual)",
        "assumptions_title": "Key Assumptions & Capacity",
        "assump_gpu_mix": "GPU Configuration",
        "assump_utilization": "Utilization Rate",
        "assump_tokens": "Tokens Serviced (Trillion)",
        "pnl_revenue": "Revenue",
        "pnl_cost_of_revenue": "Cost of Revenue",
        "pnl_gross_profit": "Gross Profit",
        "pnl_sg_and_a": "  - SG&A",
        "pnl_d_and_a": "  - D&A (DC & HW)",
        "pnl_rd_amortization": "  - R&D Amortization",
        "pnl_operating_profit": "Operating Profit",
        "section_2_title": "2. P&L by Customer Segment (Per User, Monthly)",
        "tier_free": "Free Users",
        "tier_standard": "Paid Users",
        "tier_premium": "Premium Users",
        "payback_title": "Investment Payback Period",
        "payback_years": "Estimated Payback Years",
        "unrecoverable": "Unrecoverable",
        "power_conventional": "Conventional",
        "power_renewable": "Renewable",
        "narrative_users": "Number of Users",
        "narrative_revenue_per_user": "Usage-Based Revenue",
        "narrative_cost_per_user": "Cost per User",
        "narrative_profit_per_user": "Usage-Based Profit",
        # [NEW] Pricing Strategy Section
        "sidebar_pricing_title": "💰 Pricing Strategy",
        "pricing_standard_fee": "Standard Tier Monthly Fee ($)",
        "pricing_premium_fee": "Premium Tier Monthly Fee ($)",
        "section_3_title": "3. Pricing Strategy Analysis (Per User, Monthly)",
        "narrative_pricing_title": "Analysis for",
        "narrative_fixed_fee_revenue": "Fixed-Fee Revenue",
        "narrative_opportunity_cost": "Opportunity Cost (vs. Usage-Based)",
        "narrative_new_profit_per_user": "New Profit (Fixed-Fee)",
    },
    "ko": {
        "app_title": "AI 데이터센터 사업성 시뮬레이터",
        "app_subtitle": "AI 서비스의 현실적인 손익(P&L)을 분석하는 전략 도구입니다.",
        "sidebar_guide_title": "📖 사용 방법",
        "sidebar_guide_text": "아래 변수를 조절하고 '분석 실행'을 클릭하여 재무 예측을 확인하세요.",
        "copyright_text": "© 2025, Oh Sunghwan. All rights reserved.",
        "contact_text": "문의: hawn21@gmail.com",
        "lang_selector": "언어",
        "dc_capacity": "데이터센터 용량 (MW)",
        "high_perf_gpu_ratio": "고성능 GPU 예산 비중 (%)",
        "utilization_rate": "데이터센터 평균 가동률 (%)",
        "power_type": "전력 종류",
        "apply_mirrormind": "지능형 아키텍처 적용",
        "market_price": "토큰당 시장 판매가 ($ / 1M)",
        "run_button": "🚀 분석 실행",
        "initial_prompt": "사이드바에서 시나리오 변수를 설정한 후 '분석 실행' 버튼을 눌러 결과를 확인하세요.",
        "section_1_title": "1. 전체 사업 손익 (연간 P&L)",
        "assumptions_title": "주요 가정 및 생산량",
        "assump_gpu_mix": "그래픽카드 구성",
        "assump_utilization": "평균 가동률",
        "assump_tokens": "처리 토큰 총량 (조)",
        "pnl_revenue": "매출",
        "pnl_cost_of_revenue": "매출원가",
        "pnl_gross_profit": "매출총이익",
        "pnl_sg_and_a": "  - 판매관리비",
        "pnl_d_and_a": "  - 유형자산상각비 (DC, HW)",
        "pnl_rd_amortization": "  - 무형자산상각비 (R&D)",
        "pnl_operating_profit": "영업이익",
        "section_2_title": "2. 고객 그룹별 손익 분석 (인당, 월간)",
        "tier_free": "무료 사용자",
        "tier_standard": "유료 사용자",
        "tier_premium": "프리미엄 사용자",
        "payback_title": "투자금 회수 기간",
        "payback_years": "예상 회수 기간 (년)",
        "unrecoverable": "회수 불가",
        "power_conventional": "일반 전력망",
        "power_renewable": "재생에너지",
        "narrative_users": "사용자 수",
        "narrative_revenue_per_user": "사용량 기반 매출",
        "narrative_cost_per_user": "인당 원가",
        "narrative_profit_per_user": "사용량 기반 이익",
        # [NEW] Pricing Strategy Section
        "sidebar_pricing_title": "💰 요금제 전략 설정",
        "pricing_standard_fee": "유료 사용자 월 요금 ($)",
        "pricing_premium_fee": "프리미엄 사용자 월 요금 ($)",
        "section_3_title": "3. 요금제 전략 분석 (인당, 월간)",
        "narrative_pricing_title": "분석 대상",
        "narrative_fixed_fee_revenue": "고정 요금제 매출",
        "narrative_opportunity_cost": "기회비용 (vs 사용량 기반)",
        "narrative_new_profit_per_user": "최종 이익 (고정 요금제)",
    }
}

def t(key, lang="ko", **kwargs):
    return loc_strings.get(lang, {}).get(key, key).format(**kwargs)
