import yaml

def load_config(path='config.yml'):
    """
    Loads the configuration from a YAML file.
    YAML 파일을 로드하여 설정을 불러옵니다.
    """
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        st.error(f"Error: The configuration file '{path}' was not found.")
        return None
    except Exception as e:
        st.error(f"Error loading or parsing the configuration file: {e}")
        return None
